"""
Video Consulting & Consent API
Placeholder endpoints for future Hospital HMS API integration
Supports video consultation and video consent recording
"""

from fastapi import APIRouter, HTTPException, Depends, Query
from pydantic import BaseModel, Field
from typing import Optional, List, Dict, Any
from datetime import datetime, timezone
from uuid import uuid4
import dependencies

router = APIRouter(prefix="/video-consulting", tags=["Video Consulting"])


class VideoConsentRequest(BaseModel):
    patient_id: str
    consent_type: str = Field(..., description="Type: treatment, telemedicine, data_sharing, recording")
    appointment_id: Optional[str] = None
    doctor_id: Optional[str] = None


class VideoSessionRequest(BaseModel):
    appointment_id: str
    patient_id: str
    doctor_id: str
    session_type: str = "consultation"  # consultation, follow_up, emergency


class HMSIntegrationConfig(BaseModel):
    hms_provider: str = Field(..., description="HMS provider name")
    api_endpoint: str
    api_key: Optional[str] = None
    webhook_url: Optional[str] = None


# Mock session storage (in production, use Redis/database)
active_sessions = {}


@router.post("/consent/record")
async def record_video_consent(consent_data: VideoConsentRequest):
    """
    Record video consent for a patient
    
    This endpoint creates a consent record. In production, it would:
    1. Store the consent metadata in database
    2. Integrate with video recording service
    3. Generate a signed consent certificate
    """
    db = await dependencies.get_database()
    
    consent = {
        "id": f"VC-{str(uuid4())[:8].upper()}",
        "patient_id": consent_data.patient_id,
        "consent_type": consent_data.consent_type,
        "appointment_id": consent_data.appointment_id,
        "doctor_id": consent_data.doctor_id,
        "status": "recorded",
        "recording_url": None,  # Would be populated by HMS integration
        "recorded_at": datetime.now(timezone.utc).isoformat(),
        "expires_at": None,  # Consent typically doesn't expire
        "metadata": {
            "ip_address": "recorded",
            "user_agent": "web",
            "location": "online"
        }
    }
    
    await db.video_consents.insert_one(consent)
    consent.pop("_id", None)
    
    return {
        "message": "Video consent recorded successfully",
        "consent": consent,
        "hms_integration_status": "pending_setup",
        "note": "HMS API integration required for actual video recording"
    }


@router.get("/consent/{consent_id}")
async def get_video_consent(consent_id: str):
    """Get video consent details by ID"""
    db = await dependencies.get_database()
    
    consent = await db.video_consents.find_one({"id": consent_id}, {"_id": 0})
    
    if not consent:
        raise HTTPException(status_code=404, detail="Consent record not found")
    
    return consent


@router.get("/consent/patient/{patient_id}")
async def get_patient_consents(
    patient_id: str,
    consent_type: Optional[str] = None,
    limit: int = Query(default=20, le=100)
):
    """Get all video consents for a patient"""
    db = await dependencies.get_database()
    
    query = {"patient_id": patient_id}
    if consent_type:
        query["consent_type"] = consent_type
    
    consents = await db.video_consents.find(
        query, {"_id": 0}
    ).sort("recorded_at", -1).limit(limit).to_list(limit)
    
    return {
        "patient_id": patient_id,
        "total": len(consents),
        "consents": consents
    }


@router.post("/session/create")
async def create_video_session(session_data: VideoSessionRequest):
    """
    Create a video consultation session
    
    In production, this would:
    1. Create a session with the HMS provider (100ms, Twilio, etc.)
    2. Generate room tokens for doctor and patient
    3. Return connection details
    """
    db = await dependencies.get_database()
    
    session = {
        "id": f"VS-{str(uuid4())[:8].upper()}",
        "appointment_id": session_data.appointment_id,
        "patient_id": session_data.patient_id,
        "doctor_id": session_data.doctor_id,
        "session_type": session_data.session_type,
        "status": "created",
        "room_id": f"room_{str(uuid4())[:12]}",
        "room_url": None,  # Would be populated by HMS
        "doctor_token": None,  # Would be generated by HMS
        "patient_token": None,  # Would be generated by HMS
        "recording_enabled": True,
        "created_at": datetime.now(timezone.utc).isoformat(),
        "started_at": None,
        "ended_at": None,
        "duration_seconds": None,
        "hms_provider": "pending_integration"
    }
    
    await db.video_sessions.insert_one(session)
    session.pop("_id", None)
    
    # Store in active sessions
    active_sessions[session["id"]] = session
    
    return {
        "message": "Video session created",
        "session": session,
        "connection_info": {
            "status": "hms_integration_required",
            "note": "Connect HMS provider to get room tokens",
            "supported_providers": ["100ms", "Twilio Video", "Vonage", "Daily.co", "Agora"]
        }
    }


@router.put("/session/{session_id}/start")
async def start_video_session(session_id: str):
    """Mark a video session as started"""
    db = await dependencies.get_database()
    
    result = await db.video_sessions.update_one(
        {"id": session_id},
        {"$set": {
            "status": "active",
            "started_at": datetime.now(timezone.utc).isoformat()
        }}
    )
    
    if result.modified_count == 0:
        raise HTTPException(status_code=404, detail="Session not found")
    
    return {"message": "Session started", "session_id": session_id}


@router.put("/session/{session_id}/end")
async def end_video_session(session_id: str):
    """End a video session and record duration"""
    db = await dependencies.get_database()
    
    session = await db.video_sessions.find_one({"id": session_id})
    if not session:
        raise HTTPException(status_code=404, detail="Session not found")
    
    ended_at = datetime.now(timezone.utc)
    started_at = datetime.fromisoformat(session.get("started_at", ended_at.isoformat()).replace('Z', '+00:00'))
    duration = int((ended_at - started_at).total_seconds())
    
    await db.video_sessions.update_one(
        {"id": session_id},
        {"$set": {
            "status": "completed",
            "ended_at": ended_at.isoformat(),
            "duration_seconds": duration
        }}
    )
    
    # Remove from active sessions
    active_sessions.pop(session_id, None)
    
    return {
        "message": "Session ended",
        "session_id": session_id,
        "duration_seconds": duration,
        "recording_status": "pending_processing"
    }


@router.get("/session/{session_id}")
async def get_video_session(session_id: str):
    """Get video session details"""
    db = await dependencies.get_database()
    
    session = await db.video_sessions.find_one({"id": session_id}, {"_id": 0})
    
    if not session:
        raise HTTPException(status_code=404, detail="Session not found")
    
    return session


@router.get("/sessions/active")
async def get_active_sessions():
    """Get all currently active video sessions"""
    return {
        "total_active": len(active_sessions),
        "sessions": list(active_sessions.values())
    }


@router.post("/hms/configure")
async def configure_hms_integration(config: HMSIntegrationConfig):
    """
    Configure HMS provider integration
    
    Supported providers:
    - 100ms (100ms.live)
    - Twilio Video
    - Vonage (OpenTok)
    - Daily.co
    - Agora
    - Custom/Self-hosted
    """
    db = await dependencies.get_database()
    
    # In production, validate API key with provider
    integration = {
        "id": f"HMS-{str(uuid4())[:8].upper()}",
        "provider": config.hms_provider,
        "api_endpoint": config.api_endpoint,
        "api_key_configured": bool(config.api_key),
        "webhook_url": config.webhook_url,
        "status": "pending_verification",
        "configured_at": datetime.now(timezone.utc).isoformat()
    }
    
    await db.hms_integrations.insert_one(integration)
    integration.pop("_id", None)
    
    return {
        "message": f"HMS integration configured for {config.hms_provider}",
        "integration": integration,
        "next_steps": [
            "Verify API credentials with provider",
            "Configure webhook endpoints",
            "Test video session creation",
            "Set up recording storage"
        ]
    }


@router.get("/hms/providers")
async def get_supported_hms_providers():
    """Get list of supported HMS providers for video integration"""
    return {
        "supported_providers": [
            {
                "name": "100ms",
                "website": "https://100ms.live",
                "features": ["Video Rooms", "Recording", "RTMP", "HLS"],
                "pricing": "Pay-as-you-go"
            },
            {
                "name": "Twilio Video",
                "website": "https://twilio.com/video",
                "features": ["Video Rooms", "Recording", "Composition"],
                "pricing": "Pay-as-you-go"
            },
            {
                "name": "Daily.co",
                "website": "https://daily.co",
                "features": ["Video Rooms", "Recording", "Transcription"],
                "pricing": "Free tier + Pay-as-you-go"
            },
            {
                "name": "Agora",
                "website": "https://agora.io",
                "features": ["Video/Audio", "Recording", "Interactive Live Streaming"],
                "pricing": "10,000 free minutes/month"
            },
            {
                "name": "Vonage (OpenTok)",
                "website": "https://vonage.com",
                "features": ["Video API", "Recording", "Archiving"],
                "pricing": "Pay-as-you-go"
            }
        ],
        "integration_guide": "Contact support@infuse.net.in for HMS integration assistance"
    }


@router.get("/stats")
async def get_video_consulting_stats():
    """Get video consulting statistics"""
    db = await dependencies.get_database()
    
    total_sessions = await db.video_sessions.count_documents({})
    completed_sessions = await db.video_sessions.count_documents({"status": "completed"})
    total_consents = await db.video_consents.count_documents({})
    
    # Calculate average duration
    pipeline = [
        {"$match": {"status": "completed", "duration_seconds": {"$exists": True}}},
        {"$group": {"_id": None, "avg_duration": {"$avg": "$duration_seconds"}}}
    ]
    duration_result = await db.video_sessions.aggregate(pipeline).to_list(1)
    avg_duration = duration_result[0]["avg_duration"] if duration_result else 0
    
    return {
        "total_sessions": total_sessions,
        "completed_sessions": completed_sessions,
        "active_sessions": len(active_sessions),
        "total_consents_recorded": total_consents,
        "average_session_duration_minutes": round(avg_duration / 60, 1) if avg_duration else 0,
        "hms_integration_status": "pending_setup"
    }
